# Generated by Django 5.0.4 on 2024-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='date_acceptance',
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
