# Generated by Django 5.0.4 on 2024-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_remove_response_date_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
